services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                user: admin
                uid: 1000
        image: crashtrakr-app
        container_name: crashtrakr-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - crashtrakr-network
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: crashtrakr-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - crashtrakr-network
        depends_on:
            - app

    db:
        image: postgres:16-alpine
        container_name: crashtrakr-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-crashtrakr_db}
            POSTGRES_USER: ${DB_USERNAME:-darwin_quiroz}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-admin_DB123}
        ports:
            - "5432:5432"
        volumes:
            - crashtrakr-db-data:/var/lib/postgresql/data
        networks:
            - crashtrakr-network

    node:
        image: node:lts-alpine
        container_name: crashtrakr-node
        user: "1000:1000"
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        networks:
            - crashtrakr-network
        command: sh -c "npm install && npm run dev"

networks:
    crashtrakr-network:
        driver: bridge

volumes:
    crashtrakr-db-data:
